// flow-typed signature: f9c32c028e3d261d286301826fb04c27
// flow-typed version: <<STUB>>/@yssk22/mizuki_v^1.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@yssk22/mizuki'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@yssk22/mizuki' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@yssk22/mizuki/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@yssk22/mizuki/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@yssk22/mizuki/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@yssk22/mizuki/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@yssk22/mizuki/index' {
  declare module.exports: $Exports<'@yssk22/mizuki'>;
}
declare module '@yssk22/mizuki/index.js' {
  declare module.exports: $Exports<'@yssk22/mizuki'>;
}
declare module '@yssk22/mizuki/src/index.js' {
  declare module.exports: $Exports<'@yssk22/mizuki/src/index'>;
}
