// flow-typed signature: 83798288f730046094be7eee7bcff362
// flow-typed version: <<STUB>>/@yssk22/mizuki_v^1.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@yssk22/mizuki'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@yssk22/mizuki' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@yssk22/mizuki/jest.config' {
  declare module.exports: any;
}

declare module '@yssk22/mizuki/jest.transform' {
  declare module.exports: any;
}

declare module '@yssk22/mizuki/src/date' {
  declare module.exports: any;
}

declare module '@yssk22/mizuki/src/date.test' {
  declare module.exports: any;
}

declare module '@yssk22/mizuki/src/Enum' {
  declare module.exports: any;
}

declare module '@yssk22/mizuki/src/Enum.test' {
  declare module.exports: any;
}

declare module '@yssk22/mizuki/src/environment' {
  declare module.exports: any;
}

declare module '@yssk22/mizuki/src/environment.test' {
  declare module.exports: any;
}

declare module '@yssk22/mizuki/src/events' {
  declare module.exports: any;
}

declare module '@yssk22/mizuki/src/events.test' {
  declare module.exports: any;
}

declare module '@yssk22/mizuki/src/flow' {
  declare module.exports: any;
}

declare module '@yssk22/mizuki/src/index' {
  declare module.exports: any;
}

declare module '@yssk22/mizuki/src/number' {
  declare module.exports: any;
}

declare module '@yssk22/mizuki/src/number.test' {
  declare module.exports: any;
}

declare module '@yssk22/mizuki/src/object' {
  declare module.exports: any;
}

declare module '@yssk22/mizuki/src/object.test' {
  declare module.exports: any;
}

declare module '@yssk22/mizuki/src/url' {
  declare module.exports: any;
}

declare module '@yssk22/mizuki/src/url.test' {
  declare module.exports: any;
}

declare module '@yssk22/mizuki/src/uuid' {
  declare module.exports: any;
}

// Filename aliases
declare module '@yssk22/mizuki/index' {
  declare module.exports: $Exports<'@yssk22/mizuki'>;
}
declare module '@yssk22/mizuki/index.js' {
  declare module.exports: $Exports<'@yssk22/mizuki'>;
}
declare module '@yssk22/mizuki/jest.config.js' {
  declare module.exports: $Exports<'@yssk22/mizuki/jest.config'>;
}
declare module '@yssk22/mizuki/jest.transform.js' {
  declare module.exports: $Exports<'@yssk22/mizuki/jest.transform'>;
}
declare module '@yssk22/mizuki/src/date.js' {
  declare module.exports: $Exports<'@yssk22/mizuki/src/date'>;
}
declare module '@yssk22/mizuki/src/date.test.js' {
  declare module.exports: $Exports<'@yssk22/mizuki/src/date.test'>;
}
declare module '@yssk22/mizuki/src/Enum.js' {
  declare module.exports: $Exports<'@yssk22/mizuki/src/Enum'>;
}
declare module '@yssk22/mizuki/src/Enum.test.js' {
  declare module.exports: $Exports<'@yssk22/mizuki/src/Enum.test'>;
}
declare module '@yssk22/mizuki/src/environment.js' {
  declare module.exports: $Exports<'@yssk22/mizuki/src/environment'>;
}
declare module '@yssk22/mizuki/src/environment.test.js' {
  declare module.exports: $Exports<'@yssk22/mizuki/src/environment.test'>;
}
declare module '@yssk22/mizuki/src/events.js' {
  declare module.exports: $Exports<'@yssk22/mizuki/src/events'>;
}
declare module '@yssk22/mizuki/src/events.test.js' {
  declare module.exports: $Exports<'@yssk22/mizuki/src/events.test'>;
}
declare module '@yssk22/mizuki/src/flow.js' {
  declare module.exports: $Exports<'@yssk22/mizuki/src/flow'>;
}
declare module '@yssk22/mizuki/src/index.js' {
  declare module.exports: $Exports<'@yssk22/mizuki/src/index'>;
}
declare module '@yssk22/mizuki/src/number.js' {
  declare module.exports: $Exports<'@yssk22/mizuki/src/number'>;
}
declare module '@yssk22/mizuki/src/number.test.js' {
  declare module.exports: $Exports<'@yssk22/mizuki/src/number.test'>;
}
declare module '@yssk22/mizuki/src/object.js' {
  declare module.exports: $Exports<'@yssk22/mizuki/src/object'>;
}
declare module '@yssk22/mizuki/src/object.test.js' {
  declare module.exports: $Exports<'@yssk22/mizuki/src/object.test'>;
}
declare module '@yssk22/mizuki/src/url.js' {
  declare module.exports: $Exports<'@yssk22/mizuki/src/url'>;
}
declare module '@yssk22/mizuki/src/url.test.js' {
  declare module.exports: $Exports<'@yssk22/mizuki/src/url.test'>;
}
declare module '@yssk22/mizuki/src/uuid.js' {
  declare module.exports: $Exports<'@yssk22/mizuki/src/uuid'>;
}
