// flow-typed signature: a8902473c3cef91d92c25846bbf8aecf
// flow-typed version: <<STUB>>/flow-cli_v^0.0.0-pre/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-cli' {
  declare module.exports: any;
}
