// flow-typed signature: e530dfda1450a23c8fc5e95c6c1fa493
// flow-typed version: <<STUB>>/superagent-defaults_v^0.1.14/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'superagent-defaults'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'superagent-defaults' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'superagent-defaults/component' {
  declare module.exports: any;
}

declare module 'superagent-defaults/lib/context' {
  declare module.exports: any;
}

declare module 'superagent-defaults/lib/methods' {
  declare module.exports: any;
}

declare module 'superagent-defaults/test/context.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'superagent-defaults/component.js' {
  declare module.exports: $Exports<'superagent-defaults/component'>;
}
declare module 'superagent-defaults/index' {
  declare module.exports: $Exports<'superagent-defaults'>;
}
declare module 'superagent-defaults/index.js' {
  declare module.exports: $Exports<'superagent-defaults'>;
}
declare module 'superagent-defaults/lib/context.js' {
  declare module.exports: $Exports<'superagent-defaults/lib/context'>;
}
declare module 'superagent-defaults/lib/methods.js' {
  declare module.exports: $Exports<'superagent-defaults/lib/methods'>;
}
declare module 'superagent-defaults/test/context.test.js' {
  declare module.exports: $Exports<'superagent-defaults/test/context.test'>;
}
